/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
***********************************************************************/

#include "DIALOG.h"
#include "GUI.h"
#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_exhaust_11200.h"
#include <stdio.h>
#include "ssz_common.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     	 	(GUI_ID_USER + 0x00)
#define EXHAUST_ID_BAG_A     	(GUI_ID_USER + 0x01)
#define EXHAUST_ID_BAG_B     	(GUI_ID_USER + 0x02)
#define EXHAUST_ID_IMG_SELECT   (GUI_ID_USER + 0x03)
#define EXHAUST_ID_IMG_STATE    (GUI_ID_USER + 0x04)


#define IMAGE_BAG_HEIGHT	(24)
#define IMAGE_BAGWIDTH		(160)

//medsbag
#define BAG_A			0
#define BAG_B			1

//exhaust start or stop
#define EXHAUST_START	0
#define EXHAUST_STOP	1

/*********************************************************************
*
*       Static data
*
***********************************************************************/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_scr_exhaust_11200", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },

};

static uint8_t flag_exhaust_medsbag = BAG_A;
static uint8_t flag_exhaust_start = EXHAUST_START;

static void put_exhaust_select_bag_and_action(uint8_t bag, uint8_t start_or_stop)
{
	GUI_RECT  rect;
	const char *ptr;
	int strlen;

	GUI_SetFont(get_font(14));
	GUI_SetColor(GUI_WHITE);
	if(start_or_stop == EXHAUST_START)
	{
		ptr = get_string(kStrPressStartToStartClearAir);		
	}
	else if(start_or_stop == EXHAUST_STOP)
	{
		ptr = get_string(kStrPressPauseToStopClearAir);
	}
	strlen = GUI_GetStringDistX(ptr);
	ui_rect_init_by_size(rect, 0, 0, strlen, (DISPLAY_HEIGHT - 24)/2);
	GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_TOP);

	ptr = get_string(kStrReturn);
	strlen = GUI_GetStringDistX(ptr);
	ui_rect_init_by_size(rect, 0, (DISPLAY_HEIGHT - 24)/2 + IMAGE_BAG_HEIGHT, strlen, (DISPLAY_HEIGHT - 24)/2);
	GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_BOTTOM);

	ui_rect_init_by_size(rect, 0, (DISPLAY_HEIGHT - 24)/2, DISPLAY_WIDTH, IMAGE_BAG_HEIGHT+1);
	GUI_DrawRectEx(&rect);

	if(bag == BAG_A)
	{
		ui_rect_init_by_size(rect, 1, (DISPLAY_HEIGHT - 24)/2+1, DISPLAY_WIDTH/2-1, IMAGE_BAG_HEIGHT-1);
		GUI_FillRectEx(&rect);
		ptr = get_string(kStrMedsBag1);
		GUI_SetTextMode(GUI_TM_REV);
		GUI_DispStringInRect(ptr, &rect, GUI_TA_HCENTER|GUI_TA_VCENTER);
		GUI_SetTextMode(GUI_TM_NORMAL);	
		if(start_or_stop == EXHAUST_START)
		{
			GUI_DrawBitmap(get_image(kImgExhaustPause), rect.x0+7, rect.y0+7);
		}
		else if(start_or_stop == EXHAUST_STOP)
		{
			GUI_DrawBitmap(get_image(kImgExhaustRun), rect.x0+7, rect.y0+7);
		}
		ui_rect_init_by_size(rect, DISPLAY_WIDTH/2, (DISPLAY_HEIGHT - 24)/2+1, DISPLAY_WIDTH/2-1, IMAGE_BAG_HEIGHT-1);
		GUI_SetColor(GUI_BLACK);
		GUI_FillRectEx(&rect);
		GUI_SetColor(GUI_WHITE);
		GUI_DispStringInRect(get_string(kStrMedsBag2), &rect, GUI_TA_HCENTER|GUI_TA_VCENTER);
	}
	else if(bag == BAG_B)
	{
		ui_rect_init_by_size(rect, 1, (DISPLAY_HEIGHT - 24)/2+1, DISPLAY_WIDTH/2-1, IMAGE_BAG_HEIGHT-1);
		GUI_DispStringInRect(get_string(kStrMedsBag1), &rect, GUI_TA_HCENTER|GUI_TA_VCENTER);

		ui_rect_init_by_size(rect, DISPLAY_WIDTH/2, (DISPLAY_HEIGHT - 24)/2+1, DISPLAY_WIDTH/2-1, IMAGE_BAG_HEIGHT-1);
		GUI_FillRectEx(&rect);
		GUI_SetTextMode(GUI_TM_REV);
		GUI_DispStringInRect(get_string(kStrMedsBag2), &rect, GUI_TA_HCENTER|GUI_TA_VCENTER);
		GUI_SetTextMode(GUI_TM_NORMAL);
		if(start_or_stop == EXHAUST_START)
		{
			GUI_DrawBitmap(get_image(kImgExhaustPause), rect.x0+7, rect.y0+7);
		}
		else if(start_or_stop == EXHAUST_STOP)
		{
			GUI_DrawBitmap(get_image(kImgExhaustRun), rect.x0+7, rect.y0+7);
		}	
	}
}

/*********************************************************************
*
*       Static code
*
***********************************************************************/
static void _cbDialog(WM_MESSAGE * pMsg)
{
	GUI_RECT rect;
	WM_HWIN hWin;
	int strlen;
	const char *ptr;
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
			//state image
			hWin = IMAGE_CreateEx(8, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+8, 8, 8, pMsg->hWin, WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, EXHAUST_ID_IMG_STATE);
			IMAGE_SetBitmap(hWin, get_image(kImgExhaustRun));
			WM_BringToTop(hWin);
			
			//state string
			hWin = TEXT_CreateEx(0, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+1, DISPLAY_WIDTH/2, IMAGE_BAG_HEIGHT-1, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_RIGHT,  EXHAUST_ID_BAG_A, get_string(kStrMedsBag1));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_WHITE);
			TEXT_SetTextColor(hWin, GUI_BLACK);
			
			//state string
			hWin = TEXT_CreateEx(DISPLAY_WIDTH/2, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+1, DISPLAY_WIDTH/2, IMAGE_BAG_HEIGHT-1, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_RIGHT,  EXHAUST_ID_BAG_B, get_string(kStrMedsBag2));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);
			break;
	
		case WM_PAINT:

			ui_rect_init_by_size(rect, 0, (DISPLAY_HEIGHT - 24)/2, DISPLAY_WIDTH, IMAGE_BAG_HEIGHT+1);
			GUI_DrawRectEx(&rect);
			
			ptr = get_string(kStrReturn);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 0, (DISPLAY_HEIGHT - 24)/2 + IMAGE_BAG_HEIGHT, strlen, (DISPLAY_HEIGHT - 24)/2);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_BOTTOM);
			
			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
***********************************************************************/
WM_HWIN app_scr_exhaust_11200_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}


int app_scr_exhaust_11200_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
	switch(msg->OpMethod)
	{
		case SCR_CURSER_MOVE:
			flag_exhaust_medsbag = msg->CursorIndex;
			flag_exhaust_start = msg->DItem[0];
			//WM_InvalidateWindow(hwin);
			break;

		case SCR_VALUE_ALTER:
			flag_exhaust_medsbag = msg->CursorIndex;
			flag_exhaust_start = msg->DItem[0];
			//WM_InvalidateWindow(hwin);
			break;
		default:
			break;
	}

 	return 0;	
}

void app_scr_exhaust_11200_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}


/*************************** End of file ****************************/
