/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
***********************************************************************/

#include "DIALOG.h"
#include "GUI.h"
#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_exhaust_11200.h"
#include <stdio.h>
#include "ssz_common.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     	 	(GUI_ID_USER + 0x00)
#define EXHAUST_ID_BAG_A     	(GUI_ID_USER + 0x01)
#define EXHAUST_ID_BAG_B     	(GUI_ID_USER + 0x02)
#define EXHAUST_ID_STR_ACTION   (GUI_ID_USER + 0x03)
#define EXHAUST_ID_IMG_STATE    (GUI_ID_USER + 0x04)


#define IMAGE_BAG_HEIGHT	(24)
#define IMAGE_BAGWIDTH		(160)

//medsbag
#define BAG_A			0
#define BAG_B			1

//exhaust start or stop
#define EXHAUST_START	0
#define EXHAUST_STOP	1

/*********************************************************************
*
*       Static data
*
***********************************************************************/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_scr_exhaust_11200", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },

};

static void put_exhaust_select_bag(uint8_t bag)
{
	WM_HWIN hWin;

	if(bag == BAG_A)
	{
		hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_BAG_A);
		TEXT_SetBkColor(hWin, GUI_WHITE);
		TEXT_SetTextColor(hWin, GUI_BLACK);

		hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_BAG_B);
		TEXT_SetBkColor(hWin, GUI_BLACK);
		TEXT_SetTextColor(hWin, GUI_WHITE);		
		
		hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_IMG_STATE);		
		WM_MoveChildTo(hWin, 8, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+8);
		WM_BringToTop(hWin);
	}
	else if(bag == BAG_B)
	{
		hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_BAG_B);
		TEXT_SetBkColor(hWin, GUI_WHITE);
		TEXT_SetTextColor(hWin, GUI_BLACK);

		hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_BAG_A);
		TEXT_SetBkColor(hWin, GUI_BLACK);
		TEXT_SetTextColor(hWin, GUI_WHITE);		
		
		hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_IMG_STATE);		
		WM_MoveChildTo(hWin, DISPLAY_WIDTH/2+8, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+8);
		WM_BringToTop(hWin);
	}
}


static void put_exhaust_action(uint8_t bag, uint8_t action)
{
	WM_HWIN hWin;
	put_exhaust_select_bag(bag);
	const GUI_BITMAP *bitmap;
	const char *p;
	
	if(action == EXHAUST_START)
	{
		bitmap = get_image(kImgExhaustPause);
		p = get_string(kStrPressStartToStartClearAir);
	}
	else if(action == EXHAUST_STOP)
	{
		bitmap = get_image(kImgExhaustRun);
		p = get_string(kStrPressPauseToStopClearAir);

	}
	hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_IMG_STATE);	
	IMAGE_SetBitmap(hWin, bitmap);
	WM_BringToTop(hWin);
	hWin = WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_STR_ACTION);
	TEXT_SetText(hWin, p);
}

/*********************************************************************
*
*       Static code
*
***********************************************************************/
static void _cbDialog(WM_MESSAGE * pMsg)
{
	GUI_RECT rect;
	WM_HWIN hWin;
	int strlen;
	const char *ptr;
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
			//a
			hWin = TEXT_CreateEx(1, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+1, DISPLAY_WIDTH/2-2, IMAGE_BAG_HEIGHT-1, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER,  EXHAUST_ID_BAG_A, get_string(kStrMedsBag1));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_WHITE);
			TEXT_SetTextColor(hWin, GUI_BLACK);
			
			//b
			hWin = TEXT_CreateEx(DISPLAY_WIDTH/2+1, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+1, DISPLAY_WIDTH/2-2, IMAGE_BAG_HEIGHT-1, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER,  EXHAUST_ID_BAG_B, get_string(kStrMedsBag2));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);

			//state image
			hWin = IMAGE_CreateEx(8, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2+8, 8, 8, pMsg->hWin, WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, EXHAUST_ID_IMG_STATE);
			IMAGE_SetBitmap(hWin, get_image(kImgExhaustPause));
			WM_BringToTop(hWin);

			//str
			hWin = TEXT_CreateEx(0, 0, DISPLAY_WIDTH/2, (DISPLAY_HEIGHT-IMAGE_BAG_HEIGHT)/2, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_LEFT,  EXHAUST_ID_STR_ACTION, get_string(kStrPressStartToStartClearAir));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);
			break;
	
		case WM_PAINT:
			GUI_SetFont(get_font(14));
			ui_rect_init_by_size(rect, 0, (DISPLAY_HEIGHT - 24)/2, DISPLAY_WIDTH, IMAGE_BAG_HEIGHT+1);
			GUI_DrawRectEx(&rect);
			
			ptr = get_string(kStrReturn);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 0, (DISPLAY_HEIGHT - 24)/2 + IMAGE_BAG_HEIGHT, strlen, (DISPLAY_HEIGHT - 24)/2);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_BOTTOM);
			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
***********************************************************************/
WM_HWIN app_scr_exhaust_11200_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}


int app_scr_exhaust_11200_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
	switch(msg->OpMethod)
	{
		case SCR_CURSER_MOVE:
			put_exhaust_select_bag(msg->CursorIndex);
			break;

		case SCR_VALUE_ALTER:
			put_exhaust_action(msg->CursorIndex, msg->DItem[0]);
			break;
		default:
			break;
	}

 	return 0;	
}

void app_scr_exhaust_11200_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}


/*************************** End of file ****************************/
