/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "app_scr_init_screen.h"
#include "GUI.h"
#include "ui_common.h"
#include "image_data.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_init_screen", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
	WM_HWIN hItem;
	int x, y;
    GUI_CONST_STORAGE GUI_BITMAP* mapinfo;
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			mapinfo = get_image(kImgkeywordModified);
			GUI_DrawBitmap(mapinfo, 0, 0);
			break;
	
		case WM_PAINT:
			mapinfo = get_image(kImgkeywordModified);
			GUI_DrawBitmap(mapinfo, 0, 0);
			break;  
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

WM_HWIN app_init_screen_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}


int app_init_screen_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
 	return 0;	
}

void app_init_screen_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}

/*************************** End of file ****************************/