/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************/


#include "DIALOG.h"
#include "GUI.h"
#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_histroy_15100.h"
#include <stdio.h>
#include "ssz_common.h"
#include "widget_text.h"
#include "widget_image.h"


/*********************************************************************
*
*       Defines
*
***********************************************************************/
#define ID_WINDOW_0     	(GUI_ID_USER + 0x00)

#define HISTROY_ID_TITLE	(GUI_ID_USER + 0x01)
#define HISTROY_ID_ITEM		(GUI_ID_USER + 0x02)
#define HISTROY_ID_INDEX	(GUI_ID_USER + 0x03)



/*********************************************************************
*
*       Static data
*
**********************************************************************/


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_scr_histroy_15100", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
***********************************************************************/


static void _cbDialog(WM_MESSAGE * pMsg) 
{
	GUI_RECT rect;
	WM_HWIN hWin;
	int strlen, x;
	const char *ptr;

	GUI_SetFont(get_font(14));
	ptr = "1000/1000";
	strlen = GUI_GetStringDistX(ptr);
	x = (DISPLAY_WIDTH - strlen)/2;
	
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
			//tile
			hWin = TEXT_CreateEx(0, 0, DISPLAY_WIDTH/2, 12, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_LEFT,  HISTROY_ID_TITLE, get_string(kStrLogEventAlarm));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);

			
			//item
			hWin = TEXT_CreateEx(0, 16, DISPLAY_WIDTH, DISPLAY_HEIGHT-28, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_LEFT,  HISTROY_ID_ITEM, get_string(kStrLogEventInfusionStart));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);
			TEXT_SetWrapMode(hWin, GUI_WRAPMODE_CHAR);

			//index
			hWin = TEXT_CreateEx(x, DISPLAY_HEIGHT-16, strlen, 16, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER,  HISTROY_ID_INDEX, "034/999");
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);
			break;
	
		case WM_PAINT:
			GUI_SetFont(get_font(14));

			ui_rect_init_by_size(rect, x-8-2, DISPLAY_HEIGHT-16+4, 8, 16);
			GUI_DrawBitmap(get_image(kImgLeftArrow), rect.x0, rect.y0);
			
			ui_rect_init_by_size(rect, x+strlen+2, DISPLAY_HEIGHT-16+4, 8, 16);
			GUI_DrawBitmap(get_image(kImgRightArrow), rect.x0, rect.y0);
			
			ptr = get_string(kStrReturn);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 0, DISPLAY_HEIGHT-16, strlen, 16);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_BOTTOM);
			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}


}

/*********************************************************************
*
*       Public code
*
**********************************************************************/
WM_HWIN app_scr_histroy_15100_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	
	return hWin;
}


int app_scr_histroy_15100_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
	switch(msg->OpMethod)
	{
		case SCR_CURSER_MOVE:
			
			break;

		case SCR_VALUE_ALTER:

			break;
		default:
			break;
	}
 	return 0;	
}

void app_scr_histroy_15100_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}


/*************************** End of file ****************************/
