/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
***********************************************************************/

#include "DIALOG.h"
#include "GUI.h"
#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_home_02000.h"
#include <stdio.h>
#include "ssz_common.h"
#include "widget_text.h"
#include "widget_image.h"


/*********************************************************************
*
*       Defines
*
***********************************************************************/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)

//child window id
#define CHILD_IMAGE_STATE		0
#define CHILD_TXET_STATE		1
#define CHILD_TXET_LEFT_TIME	2
#define CHILD_TXET_DOSE			3
#define CHILD_TXET_SPEED		4

//infusion state
#define INFUSION_STATE_IDLE		0
#define INFUSION_STATE_RUN		1
#define INFUSION_STATE_PAUSE	2

/*********************************************************************
*
*       Static data
*
***********************************************************************/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_home_02000", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
***********************************************************************/

static void put_left_time(uint16_t time)
{

}


static void put_infusion_state(uint8_t state)
{//width :128
	switch(state)
	{
		case INFUSION_STATE_IDLE:

			break;

		case INFUSION_STATE_RUN:

			break;

		case INFUSION_STATE_PAUSE:

			break;

		default:

			break;
	}


}


static void put_infusion_dose(uint8_t total_dose, uint8_t infusioned_dose)
{



}


static void put_infusion_seed(uint8_t infusion_speed)
{



}

static void _cbDialog(WM_MESSAGE * pMsg)
{
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
			break;
	
		case WM_PAINT:


			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
***********************************************************************/
WM_HWIN app_home_02000_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin, childwin;
	char str[20];
	int len;
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	childwin = widget_image_create(DISPLAY_WIDTH/2, 12, 16, 16, hWin, WM_CF_SHOW, get_image(kImgInfusionStop));
	ui_set_child_hwin(CHILD_IMAGE_STATE, childwin);
	childwin = widget_text_create(DISPLAY_WIDTH/2+16, 12, DISPLAY_WIDTH/2-16, 16, hWin, WM_CF_SHOW, get_string(kStrInfusionStop));
	ui_set_child_hwin(CHILD_TXET_STATE, childwin);
	
	strcpy(str, "0/0ml");
	len = strlen(str);
	str[len] = '\0';
	childwin = widget_text_create(DISPLAY_WIDTH - len , 29, len, 16, hWin, WM_CF_SHOW, str);
	ui_set_child_hwin(CHILD_TXET_DOSE, childwin);

	strcpy(str, "0.0ml/hr");
	len = strlen(str);
	str[len] = '\0';
	childwin = widget_text_create(DISPLAY_WIDTH - len, 45, len, 16, hWin, WM_CF_SHOW, str);
	ui_set_child_hwin(CHILD_TXET_SPEED, childwin);

	strcpy(str, "hr");
	len = strlen(str);
	str[len] = '\0';
	childwin = widget_text_create(0, 0, DISPLAY_WIDTH/2-len, 64, hWin, WM_CF_SHOW, "");
	ui_set_child_hwin(CHILD_TXET_LEFT_TIME, childwin);
	widget_text_set_font(childwin, get_font(88));
	widget_text_set_str(childwin, "0");

	
	return hWin;
}


int app_home_02000_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{

	switch(msg->OpMethod)
	{
		case SCR_CURSER_MOVE:

			break;

		case SCR_VALUE_ALTER:

			break;
		default:
			break;
	}
 	return 0;	
}

void app_home_02000_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}

/*************************** End of file ****************************/
