/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "app_scr_init_screen.h"
#include "GUI.h"
#include "ui_common.h"
#include "image_data.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define EXHAUST_ID_IMG_MENU     (GUI_ID_USER + 0x01)


#define MAIN_MENU_ICON_X(x)     ((64 - x)/2)
#define MAIN_MENU_ICON_Y(y)     ((64 - y)/2)
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_init_screen", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static void put_image(uint16_t image_index)
{
	const GUI_BITMAP *pbm;
         
	pbm = get_image( (ImgID) (kImgsetmenu_version+image_index) );
	IMAGE_SetBitmap(WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_IMG_MENU), pbm);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
	WM_HWIN hItem;
	int x, y;
    GUI_CONST_STORAGE GUI_BITMAP* mapinfo;
	WM_HWIN hWin;
	GUI_CONST_STORAGE GUI_BITMAP* bitmap;
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			//menu image
			bitmap = get_image(kImgsetmenu_version);
			hWin = IMAGE_CreateEx(0,0, bitmap->XSize, bitmap->YSize, pMsg->hWin, 
				                  WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, EXHAUST_ID_IMG_MENU);
			IMAGE_SetBitmap(hWin, bitmap);

			break;
	
		case WM_PAINT:
			//IMAGE_SetBitmap(WM_GetDialogItem(ui_get_current_hwin(), EXHAUST_ID_IMG_MENU), pbm);
			break;  
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

WM_HWIN app_init_screen_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}


int app_init_screen_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
	put_image(msg->SItem.DataValArray[1]);
 	return 0;	
}

void app_init_screen_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}

/*************************** End of file ****************************/